export const COMMUNITY_VALIDATION = {
  NAME_MIN_LENGTH: 3,
  NAME_MAX_LENGTH: 50,
  DESCRIPTION_MIN_LENGTH: 20,
  DESCRIPTION_MAX_LENGTH: 300,
  RULES_MAX_LENGTH: 1000,
  INVITATION_EXPIRY_DAYS: 7,
  OWNERSHIP_TRANSFER_EXPIRY_DAYS: 7,
} as const;

export const COMMUNITY_ERROR = {
  NOT_FOUND: 'COMMUNITY_NOT_FOUND',
  UNAUTHORIZED: 'COMMUNITY_UNAUTHORIZED',
  NOT_ADMIN: 'COMMUNITY_NOT_ADMIN',
  SLUG_EXISTS: 'COMMUNITY_SLUG_EXISTS',
  CATEGORY_NOT_FOUND: 'COMMUNITY_CATEGORY_NOT_FOUND',
  ALREADY_MEMBER: 'COMMUNITY_ALREADY_MEMBER',
  NOT_MEMBER: 'COMMUNITY_NOT_MEMBER',
  CANNOT_LEAVE_AS_FOUNDER: 'COMMUNITY_CANNOT_LEAVE_AS_FOUNDER',
  INVALID_IMAGE_OWNERSHIP: 'COMMUNITY_INVALID_IMAGE_OWNERSHIP',
  USER_BANNED: 'COMMUNITY_USER_BANNED',
  INVITATION_NOT_FOUND: 'COMMUNITY_INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'COMMUNITY_INVITATION_EXPIRED',
  INVITATION_ALREADY_USED: 'COMMUNITY_INVITATION_ALREADY_USED',
  JOIN_REQUEST_NOT_FOUND: 'COMMUNITY_JOIN_REQUEST_NOT_FOUND',
  JOIN_REQUEST_EXISTS: 'COMMUNITY_JOIN_REQUEST_EXISTS',
  CANNOT_REMOVE_FOUNDER: 'COMMUNITY_CANNOT_REMOVE_FOUNDER',
  CANNOT_BAN_ADMIN: 'COMMUNITY_CANNOT_BAN_ADMIN',
  REQUIRES_APPROVAL: 'COMMUNITY_REQUIRES_APPROVAL',
  OWNERSHIP_TRANSFER_NOT_FOUND: 'COMMUNITY_OWNERSHIP_TRANSFER_NOT_FOUND',
  OWNERSHIP_TRANSFER_EXPIRED: 'COMMUNITY_OWNERSHIP_TRANSFER_EXPIRED',
  OWNERSHIP_TRANSFER_ALREADY_USED: 'COMMUNITY_OWNERSHIP_TRANSFER_ALREADY_USED',
  OWNERSHIP_TRANSFER_EXISTS: 'COMMUNITY_OWNERSHIP_TRANSFER_EXISTS',
} as const;

export const COMMUNITY_ROLE = {
  FOUNDER: 'founder',
  ADMIN: 'admin',
  MEMBER: 'member',
} as const;

export const COMMUNITY_VISIBILITY = {
  PUBLIC: 'public',
  PRIVATE: 'private',
} as const;

export type CommunityVisibility = typeof COMMUNITY_VISIBILITY[keyof typeof COMMUNITY_VISIBILITY];
