export const FOLLOW_ERROR = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CANNOT_FOLLOW_SELF: 'CANNOT_FOLLOW_SELF',
  ALREADY_FOLLOWING: 'ALREADY_FOLLOWING',
  NOT_FOLLOWING: 'NOT_FOLLOWING',
  UNAUTHORIZED: 'UNAUTHORIZED',
} as const;
